---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rmissgames/noelperez.rimisszoic.live/videogame_collection
    - /bin/cp -R * $DEPLOYPATH
    - /bin/chmod 0755 $DEPLOYPATH/config
    - /bin/chmod 0755 $DEPLOYPATH/controller
    - /bin/chmod 0755 $DEPLOYPATH/logs
    - /bin/chmod 0755 $DEPLOYPATH/model
    - /bin/chmod 0755 $DEPLOYPATH/resources
    - /bin/chmod 0755 $DEPLOYPATH/config/*.php
    - /bin/chmod 0755 $DEPLOYPATH/controller/*.php
    - /bin/chmod 0755 $DEPLOYPATH/model/*.php
    - /bin/chmod 0755 -R $DEPLOYPATH/resources/
